version: "3"
name: curious-moon

volumes:
  db_data:

services:
  postgres:
    image: postgres:latest
    container_name: curious
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
      - ./source_data:/var/lib/postgresql/source_data

